import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/components/layout/Footer/page";
import { Header } from "@/components/layout/Header/page";
import ScrollLinked from "@/components/ui/scroll-linked";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${geistSans.variable} ${geistMono.variable} relative`}>
        <ScrollLinked />
        <Header />
        <div className="mt-20 md:mt-[140px] lg:mt-20 xl:mt-[100px]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
