apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-portfolio
  labels:
    app: ui-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-portfolio
  template:
    metadata:
      labels:
        app: ui-portfolio
    spec:
      containers:
        - name: ui-portfolio
          image: docker.io/quochau151/ui_portfolio:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ui-portfolio-service
spec:
  selector:
    app: ui-portfolio
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer
