name: Deploy API Production

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/deploy-api-production.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: ./api
        run: |
          docker build --platform linux/x86_64 -t quochau151/api_portfolio .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        working-directory: ./api
        run: docker push quochau151/api_portfolio

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull quochau151/api_portfolio
            docker stop api_portfolio
            docker rm api_portfolio
            docker run -dp 9011:4000 --name api_portfolio  quochau151/api_portfolio
            docker image prune -f
