name: UI CI Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "ui/**"
      - ".github/workflows/deploy-ui-production.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "ui/**"
permissions:
  contents: write
env:
  REGISTRY: docker.io
  IMAGE_NAME: quochau151/ui_portfolio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        working-directory: ./ui
        run: |
          echo "${{ secrets.UI_ENV_PRODUCTION }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        working-directory: ./ui
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_FULL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${SHORT_SHA}
          docker build -t $IMAGE_FULL .
          docker push $IMAGE_FULL
          echo "IMAGE_FULL=$IMAGE_FULL" >> $GITHUB_ENV

      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: quochau151/portfolio-manifests
          token: ${{ secrets.PAT_TOKEN }} # Personal Access Token hoặc PAT có quyền push
          path: ui

      - name: Update deployment.yaml
        working-directory: ./ui
        run: |
          sed -i "s|image: .*|image: $IMAGE_FULL|g" deployment.yaml

      - name: Commit & push changes
        working-directory: ./ui
        run: |
          git config user.name "Quochau151"
          git config user.email "tranlequochau.blc@gmail.com"
          git add deployment.yaml
          git commit -m "Update image to $IMAGE_FULL" || echo "No changes"
          git push

