name: Deploy UI Production

on:
  push:
    branches: ["main"]
    paths:
      - "ui/**"
      - ".github/workflows/deploy-ui-production.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        working-directory: ./ui
        run: |
          echo "${{ secrets.UI_ENV_PRODUCTION }}" > .env

      - name: Build Docker Image
        working-directory: ./ui
        run: |
          docker build --platform linux/x86_64 -t quochau151/ui_portfolio .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        working-directory: ./ui
        run: docker push quochau151/ui_portfolio
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull quochau151/ui_portfolio
            docker stop ui_portfolio
            docker rm ui_portfolio
            docker run -dp 9911:3000 --name ui_portfolio  quochau151/ui_portfolio
            docker image prune -f
